dist: xenial
language: python
os:
  - linux
cache:
  pip: true
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install codecov
  - pip install .[dev]
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then pip install -U black; fi
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - flake8 .
  - py.test --cov=mesa tests/ --cov-report=xml
  - if [ $PYTHON != "3.5" ];
    then black --check --exclude=mesa/cookiecutter-mesa/* .;
    fi
  # - ./tests/test_end_to_end_viz.sh  # needs to be investigated on why this took forever
after_success:
  - codecov
